# Generated by Django 6.0.1 on 2026-01-21 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('base_price', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=200)),
                ('capacity', models.PositiveIntegerField()),
                ('price_per_chair', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.EmailField(max_length=254)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('guests_count', models.PositiveIntegerField()),
                ('chairs_cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('food_cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('event_cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Rejected', 'Rejected')], default='Pending', max_length=30)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.eventtype')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.venue')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price_per_head', models.PositiveIntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('menu_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.menucategory')),
            ],
        ),
        migrations.CreateModel(
            name='BookingMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.booking')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.menuitem')),
            ],
            options={
                'unique_together': {('booking', 'menu_item')},
            },
        ),
    ]
